### PR TITLE
Allow to specify name of the destroyAction

### PR DESCRIPTION
**Pull request by harmjanblok**
Some organisations have renamed the destroy action, in our case to 'Destroy Deployment'. With this change the default will still be `Destroy`, but can be defined to any custom value.

### CODE REVIEW

**Comment by harmjanblok** [comment]
@Prativa20 @markpeek can you assist me with the clabot? Tried multiple times, but still seem to have it wrong.

**Comment by markpeek** [comment]
@harmjanblok just looked at your branch. Your commit and signature match so I'm not sure why the clabot is complaining. @Prativa20 can merge after reviewing the change.

**Review by Prativa20 — APPROVED** [review]
Looks good!

**Comment by harmjanblok** [comment]
@Prativa20 is it possible to release a v3.0.3 version which includes this change?

**Pull request merged**
