### PR TITLE
Update change log for release v3.0.1

### PR DESCRIPTION
**Pull request by Prativa20**
Signed-off-by: Prativa Bawri <bawrip@vmware.com>

### CODE REVIEW

**Comment by hobovirtual** [comment]
hi @Prativa20 and @markpeek 

the provider is not publish on the registry yet, i don't see any of the binaries in the latest version, not sure if it's the issue or something else within the chain that broke/missing.

thanks for your support!
image

**Comment by markpeek** [comment]
This is an issue with how it was released in github. I'll work with @Prativa20 to get it resolved today.

**Comment by markpeek** [comment]
@hobovirtual this has been fixed and you should see v3.0.1 [here](https://registry.terraform.io/providers/vmware/vra7/latest).

**Comment by hobovirtual** [comment]
awesome thanks @markpeek  and @Prativa20 for your support!

**Pull request merged**
