### PR TITLE
Migrating to the Terraform Plugin SDk.

### PR DESCRIPTION
**Pull request by lazzurs**
Migrating to the Terraform Plugin SDK using the automated migration
tool. Build passes and no issues with the migration tool.

### CODE REVIEW

**Comment by markpeek** [comment]
Thank you for the PR. `make lint` failed. Likely need to tweak errcheck.sh similar to this [change](https://github.com/vmware/terraform-provider-vra/commit/cc9a5f05c378b9c4793a90fe597041708cf58f00#diff-7ca5098cb743799af049a4af918b0598) in the vra provider.

**Comment by markpeek** [comment]
@lazzurs please back out that last commit to use "_" assignment and check the change I indicated in my comment to make this work.

**Comment by lazzurs** [comment]
Made the requested changes.

**Comment by lazzurs** [comment]
@markpeek tests now passing.

**Comment by lazzurs** [comment]
This is a very old PR that was never merged and there is now another PR in the queue to do the same thing.

Closing but if you want me to update the provider I would be happy to do it again if it is going to be merged and released.

**Pull request closed without merging**
